apiVersion: v1
kind: Service
metadata:
  name: swe645-service
spec:
  selector:
    app: swe645-web-service
    namespace: default
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
